import { param } from "../ast/expression.ts"
import type {
  CTENode,
  ExpressionNode,
  InsertMode,
  InsertNode,
  OnConflictNode,
  SelectNode,
  TableRefNode,
} from "../ast/nodes.ts"
import { createInsertNode } from "../ast/nodes.ts"
import { parseTableRef } from "../utils/table-ref.ts"

export class InsertBuilder {
  private node: InsertNode
  private paramIndex: number

  constructor(node?: InsertNode, paramIndex = 0) {
    this.node = node ?? createInsertNode({ type: "table_ref", name: "" })
    this.paramIndex = paramIndex
  }

  into(table: string | TableRefNode): InsertBuilder {
    const ref: TableRefNode = typeof table === "string" ? parseTableRef(table) : table
    return new InsertBuilder({ ...this.node, table: ref }, this.paramIndex)
  }

  columns(...cols: string[]): InsertBuilder {
    return new InsertBuilder(
      { ...this.node, columns: [...this.node.columns, ...cols] },
      this.paramIndex,
    )
  }

  values(...vals: unknown[]): InsertBuilder {
    let idx = this.paramIndex
    const row: ExpressionNode[] = vals.map((v) => {
      const p = param(idx, v)
      idx++
      return p
    })
    return new InsertBuilder({ ...this.node, values: [...this.node.values, row] }, idx)
  }

  returning(...exprs: ExpressionNode[]): InsertBuilder {
    return new InsertBuilder(
      { ...this.node, returning: [...this.node.returning, ...exprs] },
      this.paramIndex,
    )
  }

  onConflictDoNothing(...columns: string[]): InsertBuilder {
    const conflict: OnConflictNode = {
      columns,
      action: "nothing",
    }
    return new InsertBuilder({ ...this.node, onConflict: conflict }, this.paramIndex)
  }

  onConflictDoUpdate(
    columns: string[],
    set: { column: string; value: ExpressionNode }[],
    where?: ExpressionNode,
  ): InsertBuilder {
    const conflict: OnConflictNode = {
      columns,
      action: { set },
      where,
    }
    return new InsertBuilder({ ...this.node, onConflict: conflict }, this.paramIndex)
  }

  /** ON CONFLICT ON CONSTRAINT name DO NOTHING */
  onConflictConstraintDoNothing(constraint: string): InsertBuilder {
    const conflict: OnConflictNode = {
      columns: [],
      constraint,
      action: "nothing",
    }
    return new InsertBuilder({ ...this.node, onConflict: conflict }, this.paramIndex)
  }

  /** ON CONFLICT ON CONSTRAINT name DO UPDATE SET ... */
  onConflictConstraintDoUpdate(
    constraint: string,
    set: { column: string; value: ExpressionNode }[],
    where?: ExpressionNode,
  ): InsertBuilder {
    const conflict: OnConflictNode = {
      columns: [],
      constraint,
      action: { set },
      where,
    }
    return new InsertBuilder({ ...this.node, onConflict: conflict }, this.paramIndex)
  }

  /** Set insert mode (SQLite: INSERT OR IGNORE, INSERT OR REPLACE, etc.) */
  mode(mode: InsertMode): InsertBuilder {
    return new InsertBuilder({ ...this.node, insertMode: mode }, this.paramIndex)
  }

  /** Shorthand: INSERT OR IGNORE (SQLite) */
  orIgnore(): InsertBuilder {
    return this.mode("INSERT OR IGNORE")
  }

  /** Shorthand: INSERT OR REPLACE (SQLite) */
  orReplace(): InsertBuilder {
    return this.mode("INSERT OR REPLACE")
  }

  /** MySQL: ON DUPLICATE KEY UPDATE */
  onDuplicateKeyUpdate(set: { column: string; value: ExpressionNode }[]): InsertBuilder {
    return new InsertBuilder({ ...this.node, onDuplicateKeyUpdate: set }, this.paramIndex)
  }

  /** INSERT INTO ... SELECT ... */
  fromSelect(query: SelectNode): InsertBuilder {
    return new InsertBuilder({ ...this.node, source: query }, this.paramIndex)
  }

  /**
   * `OVERRIDING SYSTEM VALUE` — explicitly let an INSERT provide a
   * value for a column declared `GENERATED ALWAYS AS IDENTITY`, which
   * normally rejects user-supplied values. PG-only (SQL:2003). MySQL /
   * SQLite have no equivalent and the printer rejects; MSSQL has the
   * separate `SET IDENTITY_INSERT` statement.
   */
  overridingSystemValue(): InsertBuilder {
    return new InsertBuilder({ ...this.node, overriding: "SYSTEM" }, this.paramIndex)
  }

  /**
   * `OVERRIDING USER VALUE` — force the system-generated value even
   * when the user supplied a value for a column declared `GENERATED BY
   * DEFAULT AS IDENTITY`. PG-only (SQL:2003).
   */
  overridingUserValue(): InsertBuilder {
    return new InsertBuilder({ ...this.node, overriding: "USER" }, this.paramIndex)
  }

  /**
   * INSERT INTO ... DEFAULT VALUES.
   *
   * Clears any previously-added `values` / `columns` / `source` so
   * subsequent conflicting build state doesn't silently win in the
   * printer (which prefers `defaultValues` over both `source` and
   * `values`).
   */
  defaultValues(): InsertBuilder {
    return new InsertBuilder(
      { ...this.node, defaultValues: true, columns: [], values: [], source: undefined },
      this.paramIndex,
    )
  }

  with(name: string, query: SelectNode, recursive = false): InsertBuilder {
    const cte: CTENode = { name, query, recursive }
    return new InsertBuilder({ ...this.node, ctes: [...this.node.ctes, cte] }, this.paramIndex)
  }

  build(): InsertNode {
    return { ...this.node }
  }
}

export function insert(table: string | TableRefNode): InsertBuilder {
  return new InsertBuilder().into(table)
}
