import { writeFile } from "node:fs/promises"
import { resolve } from "node:path"

import { planMigration } from "../../migrate/runner.ts"
import { sumak } from "../../sumak.ts"
import type { SumakConfig } from "../config.ts"
import { loadDialect } from "../dialect.ts"
import { introspectForMigrate } from "./introspect-runtime.ts"

/**
 * `sumak generate` — emit the SQL that would turn the live database
 * into the TypeScript schema, without running it. Equivalent to
 * `sumak migrate plan > file.sql` but with an opinionated file
 * layout (one statement per line, timestamped header).
 *
 * The SQL is printed to stdout unless `--out <path>` or `outFile` is
 * set, in which case it's written to that file.
 */
export async function generateCommand(
  config: SumakConfig,
  args: {
    readonly flags: Readonly<Record<string, string | boolean>>
    readonly positional: readonly string[]
  },
): Promise<void> {
  const driver = await config.driver()
  const schemaOrDb = await config.schema()
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const tables = (
    "tables" in schemaOrDb && typeof schemaOrDb.tables === "object"
      ? (schemaOrDb as { tables: unknown }).tables
      : (schemaOrDb as unknown as { _config: { tables: unknown } })._config.tables
  ) as any

  const dialect = loadDialect(config.dialect)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const db = sumak({ dialect, driver, tables }) as any
  const before = await introspectForMigrate(driver, config.dialect, config.namespace)

  const allowDestructive = args.flags["allow-destructive"] === true
  const plan = planMigration(db, before, tables, { allowDestructive })

  const header = `-- generated by sumak at ${new Date().toISOString()}\n-- dialect: ${config.dialect}\n\n`
  const body = plan.steps.map((s) => `${s.sql};\n`).join("\n")
  const out = header + body

  const outFlag = args.flags.out
  const outFile = typeof outFlag === "string" ? outFlag : config.outFile
  if (!outFile) {
    process.stdout.write(out)
    return
  }
  const abs = resolve(process.cwd(), outFile)
  await writeFile(abs, out, "utf8")
  process.stderr.write(`✓ wrote ${plan.steps.length} statement(s) → ${abs}\n`)
}
